Self-service Password Reset/Controllers/PasswordRequestsController.cs
using Self_service_Password_Reset.Models;
using System;
using System.Collections.Generic;
using System.DirectoryServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Self_service_Password_Reset.Controllers
{
    public class PasswordRequestsController : Controller
    {
        private SSPREntities db = new SSPREntities();
        //private Self_service_Password_ResetContext db = new Self_service_Password_ResetContext();

        // GET: PasswordRequests
        public ActionResult Index()
        {
            return View();
        }

        // GET: PasswordRequests/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PasswordRequests/Create
        public ActionResult Create(string userName)
        {
            string message = "";

            if (userName == null)
            {
                message = "User Name not specified";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Error", messageDescription = @message, redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 3 });
            }

            //Hint hint = new Hint();
            List<Hint> hints = new List<Hint>();
            string encryptedUserName = Helpers.EncryptData(userName.Trim().ToUpper());

            hints = db.Hints.Where(u => u.UserName == encryptedUserName).ToList();

            if (hints.Count() < 4)
            {
                message = "User not configured for password self reset";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Warning", messageDescription = @message, redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 2 });
            }


            int[] questions;
            questions = Helpers.UniqueRandomNumber(3, 1, hints.Count());

            List<Hint> choosenHints = new List<Hint>();
            Hint hint = new Hint();

            foreach (int question in questions)
            {
                hint = hints[question - 1];
                //Clears answer so that they're not submitted to client and decrypts questions
                hint.Question = Helpers.DecryptData(hint.Question);
                hint.Answer = "";
                choosenHints.Add(hint);
            }

            return View(choosenHints);
        }

        // POST: PasswordRequests/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string message = "";

                bool cancel = false;

                string userName = Helpers.DecryptData(collection["UserName"].Split(',')[0]);

                string password1 = collection["Password1"];
                string password2 = collection["Password2"];

                int question1 = 0;
                int question2 = 0;
                int question3 = 0;

                int.TryParse(collection["Question1"], out question1);
                int.TryParse(collection["Question2"], out question2);
                int.TryParse(collection["Question3"], out question3);

                string answer1 = collection["Answer1"].Trim().ToUpper();
                string answer2 = collection["Answer2"].Trim().ToUpper();
                string answer3 = collection["Answer3"].Trim().ToUpper();

                Hint hint1 = db.Hints.Where(h => h.ID == question1).FirstOrDefault();
                Hint hint2 = db.Hints.Where(h => h.ID == question2).FirstOrDefault();
                Hint hint3 = db.Hints.Where(h => h.ID == question3).FirstOrDefault();

                //Handles answers
                if ((cancel == false) && ((!Helpers.IsAnswerCorrect(hint1.Answer, answer1)) || (!Helpers.IsAnswerCorrect(hint2.Answer, answer2)) || (!Helpers.IsAnswerCorrect(hint3.Answer, answer3))))
                {
                    message = message + "Security questions answered incorrectly";
                    cancel = true;
                }

                //Handles mismatch passwords
                if ((cancel == false) && (password1 != password2))
                {
                    message = message + "Passwords do not match";
                    cancel = true;
                }

                //Handles insecure passwords
                if (cancel == false)
                {
                    bool valid = false;
                    string patternMatch = "";

                    Helpers.IsPasswordSecure(password1, out valid, out patternMatch);

                    if (valid == false)
                    {
                        message = message + "Password not secure, cannot contain " + patternMatch;
                        cancel = true;
                    }
                }

                if (cancel == true)
                {
                    return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Warning", messageDescription = @message, redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 2 });
                }
                //If all checks passed, attemps password change
                else
                {
                    bool resetted = false;
                    try
                    {

                        string _domainFQDN = System.Configuration.ConfigurationManager.AppSettings["DomainFQDN"];
                        string _domainNetBIOS = System.Configuration.ConfigurationManager.AppSettings["DomainNetBIOS"];
                        string _connectionUserName = System.Configuration.ConfigurationManager.AppSettings["ConnectionUserName"];
                        string _connectionPassword = System.Configuration.ConfigurationManager.AppSettings["ConnectionPassword"];

                        using (DirectoryEntry de = new DirectoryEntry("LDAP://" + _domainFQDN, _domainNetBIOS + @"\" + _connectionUserName, _connectionPassword))
                        using (DirectorySearcher ds = new DirectorySearcher(de))
                        {

                            SearchResultCollection src;

                            ds.PageSize = 1000;
                            ds.PropertiesToLoad.Add("cn");
                            ds.PropertiesToLoad.Add("distinguishedName");
                            ds.PropertiesToLoad.Add("sAMAccountName");
                            ds.PropertiesToLoad.Add("userPrincipalName");
                            ds.PropertiesToLoad.Add("userAccountControl");
                            ds.PropertiesToLoad.Add("lockoutTime");
                            ds.Filter = "(&(userPrincipalName=" + userName + "))";
                            //ds.Filter = "(&(sAMAccountName=bsmith))";
                            ds.Sort.Direction = System.DirectoryServices.SortDirection.Ascending;
                            ds.Sort.PropertyName = "cn";
                            src = ds.FindAll();

                            foreach (SearchResult sr in src)
                            {
                                DirectoryEntry user = sr.GetDirectoryEntry();
                                user.Invoke("SetPassword", new object[] { password1 });

                                //********** Start of unlock user account
                                //try
                                //{
                                //    if (user.Properties.Contains("userAccountControl"))
                                //    {
                                //        int m_Val = (int)user.Properties["userAccountControl"][0];
                                //        de.Properties["userAccountControl"].Value = m_Val | 0x0001;
                                //        de.CommitChanges();
                                //    }
                                //}
                                //catch (Exception ex)
                                //{

                                //}
                                try
                                {
                                    user.Properties["LockOutTime"].Value = 0;
                                    user.CommitChanges();
                                }
                                catch (Exception ex)
                                {
                                    return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Error", messageDescription = ex.Message, redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 50, messageType = 3 });
                                }
                                //********** End of unlock user account

                                resetted = true;
                                break;
                            }
                        }

                        if (resetted == true)
                        {
                            return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Success", messageDescription = "Password changed successfully", redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 1 });
                        }
                        else
                        {
                            return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Not found", messageDescription = "User account not found", redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 2 });
                        }
                    }
                    catch (Exception ex)
                    {
                        return RedirectToAction("DisplayMessage", "Home", new { title = "Reset Password", messageTitle = "Error", messageDescription = ex.Message, redirectTo = "../PasswordRequests/SpecifyUser", redirectDelay = 5, messageType = 3 });
                    }

                }
            }
            catch
            {

Self-service Password Reset/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Self-service password reset (SSPR)</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href='~/Content/strength/strength.css' rel='stylesheet' type='text/css'>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/strength/strength.js"></script>
    <script>
        $(document).ready(function ($) {

            $('#myPassword').strength();

        });

    </script>
    @RenderSection("HeadScripts", required: false)
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <a href="@Url.Action("Index", "Home")">
                    <img style="width: 226px; height: 191px; border: none; vertical-align: middle" src="~/Content/Images/Logo.png" />
                </a>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        <li>@Html.ActionLink("Hints", "Index", "Hints")</li>
                        <li>@Html.ActionLink("Reset Password", "SpecifyUser", "PasswordRequests")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Self-service password reset (SSPR)</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-ui-1.10.4.min.js")
    @Scripts.Render("~/Scripts/functions.js")
    @RenderSection("scripts", required: false)
</body>
</html>