Self-service Password Reset/Controllers/HintsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Self_service_Password_Reset;
using Self_service_Password_Reset.Models;

namespace Self_service_Password_Reset.Controllers
{
    [Authorize]
    public class HintsController : Controller
    {
        private SSPREntities db = new SSPREntities();
        //private Self_service_Password_ResetContext db = new Self_service_Password_ResetContext();

        // GET: Hints
        public ActionResult Index()
        {
            //string userName = Helpers.EncryptData("TEST");
            string userName = Helpers.EncryptData(User.Identity.Name.Trim().ToUpper());

            List<Hint> hints = db.Hints.Where(h => h.UserName == userName).ToList();
            foreach (Hint hint in hints)
            {
                hint.Question = Helpers.DecryptData(hint.Question);
                hint.Answer = "";
            }
            return View(hints);
        }

        // GET: Hints/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hint hint = db.Hints.Find(id);
            hint.Question = Helpers.DecryptData(hint.Question);
            if (hint == null)
            {
                return HttpNotFound();
            }

            if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
            {
                string message = "Not allowed to create/view/edit/delete other users hints";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
            }

            return View(hint);
        }

        // GET: Hints/Create
        public ActionResult Create()
        {
            Hint hint = new Hint();
            //hint.UserName = Helpers.EncryptData("TEST");
            hint.UserName = Helpers.EncryptData(User.Identity.Name.Trim().ToUpper());
            return View(hint);
        }

        // POST: Hints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserName,Question,Answer")] Hint hint)
        {
            if (ModelState.IsValid)
            {
                if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
                {
                    string message = "Not allowed to create/view/edit/delete other users hints";
                    return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
                }

                hint.Question = Helpers.EncryptData(hint.Question);
                hint.Answer = Helpers.HashWithSalt(hint.Answer);

                db.Hints.Add(hint);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hint);
        }

        // GET: Hints/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hint hint = db.Hints.Find(id);
            hint.Question = Helpers.DecryptData(hint.Question);
            hint.Answer = "";

            if (hint == null)
            {
                return HttpNotFound();
            }

            if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
            {
                string message = "Not allowed to create/view/edit/delete other users hints";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
            }

            return View(hint);
        }

        // POST: Hints/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,Question,Answer")] Hint hint)
        {
            if (ModelState.IsValid)
            {
                if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
                {
                    string message = "Not allowed to create/view/edit/delete other users hints";
                    return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
                }

                hint.Question = Helpers.EncryptData(hint.Question);
                hint.Answer = Helpers.HashWithSalt(hint.Answer);

                db.Entry(hint).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hint);
        }

        // GET: Hints/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hint hint = db.Hints.Find(id);
            hint.Question = Helpers.DecryptData(hint.Question);
            if (hint == null)
            {
                return HttpNotFound();
            }

            if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
            {
                string message = "Not allowed to create/view/edit/delete other users hints";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
            }

            return View(hint);
        }

        // POST: Hints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hint hint = db.Hints.Find(id);

            if (hint.UserName != Helpers.EncryptData(User.Identity.Name.Trim().ToUpper()))
            {
                string message = "Not allowed to create/view/edit/delete other users hints";
                return RedirectToAction("DisplayMessage", "Home", new { title = "Hints", messageTitle = "Warning", messageDescription = @message, redirectTo = "../Hints/Index", redirectDelay = 5, messageType = 2 });
            }

            db.Hints.Remove(hint);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Self-service Password Reset/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Self_service_Password_Reset;
using Self_service_Password_Reset.Models;

namespace Self_service_Password_Reset.Controllers
{
    public class QuestionsController : Controller
    {
        private SSPREntities db = new SSPREntities();
        //private Self_service_Password_ResetContext db = new Self_service_Password_ResetContext();

        public ActionResult QuestionSearch(string term)
        {
            //var _questions = db.Questions.Select(b => new { label = b.Value }).Distinct().Take(10);
            var _questions = db.Questions.Where(q => q.Value.Contains(term)).OrderBy(q => q.Value).Select(b => new { label = b.Value }).Distinct().Take(10);
            return Json(_questions, JsonRequestBehavior.AllowGet);
        }
        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Value")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Value")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Self-service Password Reset/Views/Hints/Create.cshtml
@model Self_service_Password_Reset.Hint

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hint</h4>
        <hr />
        @Html.HiddenFor(model => model.UserName)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@Model.Question" name="Question" data-autocomplete="@Url.Action("QuestionSearch", "Questions")" style="width:500px" />
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Self-service Password Reset/Views/Hints/Delete.cshtml
@model Self_service_Password_Reset.Hint

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hint</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            Answer is securely stored and cannot be decrypted
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Self-service Password Reset/Views/Hints/Details.cshtml
@model Self_service_Password_Reset.Hint

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Hint</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            Answer is securely stored and cannot be decrypted
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Self-service Password Reset/Views/Hints/Edit.cshtml
@model Self_service_Password_Reset.Hint

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Answer is securely stored and cannot be decrypted, you can however change it if you choose to</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.UserName)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@Model.Question" name="Question" data-autocomplete="@Url.Action("QuestionSearch", "Questions")" style="width:500px" />
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Self-service Password Reset/Views/Hints/Index.cshtml
@model IEnumerable<Self_service_Password_Reset.Hint>

    @{
        ViewBag.Title = "Hints";
    }

    <h2>@ViewBag.Title</h2>

    <p>
        You need to configure at least <b>four hints</b> to be able to recover account later
    </p>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Question)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>